version: '3.9'
services:
  mysql:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: backend
      MYSQL_PASSWORD: '123456'