version: '3.9'
services:
  backend:
    build: .
    user: node
    container_name: backend
    tty: true
    stdin_open: true
    command: npm run dev
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    restart: always
    environment:
      DB_USER: root
      DB_PASSWORD: '123456'
      DB_HOST: db
      DB_PORT: 3306
      JWT_SECRET: secret
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: backend
      MYSQL_PASSWORD: '123456'